name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    bronze:
      +materialized: view
      +database: bronze
      +tags: ['bronze']
      
    silver:
      +materialized: table
      +database: silver
      +tags: ['silver']
      
    gold:
      +materialized: table
      +database: gold
      +tags: ['gold']